# Generated by Django 5.2.14 on 2026-06-01 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(max_length=255)),
                ('ranking', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('rating_change', models.FloatField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('total_problems', models.IntegerField(default=0)),
                ('attended_at', models.DateTimeField()),
                ('finish_time_in_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attended_at'],
                'unique_together': {('user', 'contest_title')},
            },
        ),
    ]
