# Generated by Django 5.2.14 on 2026-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='strong_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='total_solved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='weak_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='roadmap',
            field=models.JSONField(default=dict),
        ),
    ]
