# Generated by Django 5.2.14 on 2026-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmap_ranking_roadmap_strong_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='completed_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
